### PR TITLE
docs: add Simplified Chinese `zh-CN` translation

### PR DESCRIPTION
**Pull request by caelyreth**
### Description

- add zh locales to the docs project with the Vitepress' built-in locales support
- add `zh-CN` translation based on v0.10.0-beta9
- a translation checkpoint indicator after documentation like Vue Router docs's

### Status

- [x] Guide
- [x] Intergrations
- [x] References

Every translated file's line numbers have been aligned to the EN version.

**Please review those changes, thanks.**

### Preview Link

[Netlify PR Preview](https://deploy-preview-109--shikiji.netlify.app/)

### CODE REVIEW

**Comment by ifshizuku** [comment]
Referring to the Chinese translation of Vue Router, I created a Checkpoint indicator after the document. The implementation details are similar to the flow used by the Vue Router project.

image

**Comment by antfu** [comment]
Hey, thank you for working on this. Unfortunately, I don't have the bandwidth to maintain translations. Maybe it might be better to host it in your personal account, and we could link it as a community translation.

**Comment by ifshizuku** [comment]
> Hey, thank you for working on this. Unfortunately, I don't have the bandwidth to maintain translations. Maybe it might be better to host it in your personal account, and we could link it as a community translation.



> Hey, thank you for working on this. Unfortunately, I don't have the bandwidth to maintain translations. Maybe it might be better to host it in your personal account, and we could link it as a community translation.

That's OK, I'll do it later. I will let you know when my own site translation is available.

**Comment by ifshizuku** [comment]
@antfu Should I keep a complete copy of the corresponding English version on my website?

And one thing to note is that separate sites seem to make version synchronization and comparison cumbersome, (I used to have this problem when translating Next.js).

Personally, I could keep maintenance on this document for a long time, keep it synchronized at a frequency of once or twice a week, and perhaps have better versioning in the original repository.

But if you feel better about manually syncing these within my account, I'll start the migration at the same time.

**Comment by ifshizuku** [comment]
Right now I'm working on building a proper synchronization scheme to version control my repository in a timely manner.

**Comment by ifshizuku** [comment]
I spent some time outside of school trying to quickly migrate it, and found that stripping the documentation out of the original project ran into a host of dependencies and other vitepress runtime issues. Because of time issues, I'll continue to finish it over the weekend, at which point I'll synchronize the changes to the latest weekend commit to translate it.

Apologies for not being able to make my own page available in time.

**Comment by antfu** [comment]
No worries, take your time :)

**Comment by antfu** [comment]
We have moved back to Shiki https://github.com/shikijs/shiki, if later you finished the translation, feel free to open PR there to add the link. Thanks!

**Comment by ifshizuku** [comment]
Should I host in my own repo the same? Or does the new organization have the time to maintain it? @antfu

**Pull request closed without merging**
